_Indexing_

In [1]:
import numpy as np

# One dimensional array
A = np.array([10, 21, 32, 43, 54, 65, 76, 87])

# Print the first element of A
print(A[0])

10


In [2]:
print(A[-1])

87


In [3]:
print(A[2])

32


In [4]:
print(A[-2])

76


In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
print(A[0][0])

1


_Slicing_

In [8]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(A[:4])

[1 2 3 4]


In [9]:
print(A[6:])

[7 8]


In [10]:
print(A[2:5])

[3 4 5]


In [11]:
print(A[:])

[1 2 3 4 5 6 7 8]


In [12]:
print(A[::2])

[1 3 5 7]


In [13]:
print(A[::3])

[1 4 7]


In [14]:
A = np.array([
    ["00", "01", "02", "03", "04"],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
    [40, 41, 42, 43, 44]
])

print(A)

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']
 ['20' '21' '22' '23' '24']
 ['30' '31' '32' '33' '34']
 ['40' '41' '42' '43' '44']]


In [15]:
print(A[1, ])  # Printing Row 2

['10' '11' '12' '13' '14']


In [16]:
print(A[:, 1])  # Column 2

['01' '11' '21' '31' '41']


In [17]:
print(A[:2, ])  # Rows 1 & 2

print(A[:, 1:3])  # Columns 2 & 3

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']]
[['01' '02']
 ['11' '12']
 ['21' '22']
 ['31' '32']
 ['41' '42']]


In [18]:
print(A[:3, ])  # Printing first three rows

print(A[:, 3:])  # Printing 4th column and onwards

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']
 ['20' '21' '22' '23' '24']]
[['03' '04']
 ['13' '14']
 ['23' '24']
 ['33' '34']
 ['43' '44']]


_Using step_

In [19]:
A2 = np.arange(50).reshape(5, 10)

print(A2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [20]:
print(A2[::2, ])  # Print rows 1, 3, and 5

[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]
 [40 41 42 43 44 45 46 47 48 49]]


In [21]:
print(A2[:, 1:5:2])  # Print columns 2 & 4

[[ 1  3]
 [11 13]
 [21 23]
 [31 33]
 [41 43]]


_Array of ones and zeros_

In [22]:
O = np.ones((4,4))
print(O)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
Z = np.zeros((3, 3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
Z = np.zeros((3,3), dtype = int)
print(Z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
_Identity function_

In [25]:
I = np.identity(4)

print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
I = np.identity(3, dtype=int)

print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
