In [4]:
import numpy as np
stock_values = [20.3, 25.3, 22.7, 19.0, 18.5, 21.2, 24.5, 26.6, 23.2, 21.2]
SV = np.array(stock_values)

print (SV)
type(SV)

[20.3 25.3 22.7 19.  18.5 21.2 24.5 26.6 23.2 21.2]


numpy.ndarray

In [5]:
stockvalues = (20.3, 25.3, 22.7, 19.0, 18.5, 21.2, 24.5, 26.6, 23.2, 21.2) # This is a tuple

# Converting tuple into an array

S_V = np.array(stockvalues) 

print (S_V)
type(S_V)

[20.3 25.3 22.7 19.  18.5 21.2 24.5 26.6 23.2 21.2]


numpy.ndarray

In [7]:
# If the start parameter is not given, it will be set to 0

# '10' is the stop parameter

# The default interval for a step is '1'

# If the 'dtype' is not given, then it will be automatically inferred from the other input arguments

a = np.arange (10) # Syntax a = np.arange (0,10,1,None)
print (a)
type(a)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [8]:
b = np.arange (1,15)
print (b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [9]:
# We have changed the 'step' or spacing between two adjacent values, from a default 1, to a user given value of 2

c = np.arange (0,21,2)
print (c)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [10]:
d = np.arange (1.3,23.3,2.1,int)
print (d)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [11]:
d = np.arange (1.3,23.3,2.1,float)
print (d)

[ 1.3  3.4  5.5  7.6  9.7 11.8 13.9 16.  18.1 20.2 22.3]


In [12]:
a = np.linspace (1,10)
print (a)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [29]:
c = np.linspace (1,10,8)
print (c)
print ("The dimension of array 'a' is", np.ndim (c))
print ("The datatype of array 'a' is", c.dtype)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]
The dimension of array 'a' is 1
The datatype of array 'a' is float64


In [15]:
c = np.linspace (1,10,8,False)
print (c)

[1.    2.125 3.25  4.375 5.5   6.625 7.75  8.875]


In [16]:
d = np.linspace (1,10,8,True,True)
print (d)

(array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ]), 1.2857142857142858)


In [30]:
e = np.linspace(1,10,10,True,True)
print (e)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


In [31]:
# Scalar

a = np.array (50) #Should have only 1 element, at the maximum!

print ("a:", a)
type(a)
print ("The dimension of array 'a' is", np.ndim (a))
print ("The datatype of array 'a' is", a.dtype)
print (a, np.ndim (a), a.dtype)

a: 50
The dimension of array 'a' is 0
The datatype of array 'a' is int64
50 0 int64


In [39]:
# One-dim array

a = np.array([1, 1, 2, 3, 5, 8, 13, 21]) # Fibonnacci series
b = np.array([4.4, 6.6, 8.8, 10.1, 12.12])

print("a: ", a)
print("b: ", b)

print("Type of 'a': ", a.dtype)
print("Type of 'b': ", b.dtype)

print("Dimension of 'a':", np.ndim(a))
print("Dimension of 'b':", np.ndim(b))

a:  [ 1  1  2  3  5  8 13 21]
b:  [ 4.4   6.6   8.8  10.1  12.12]
Type of 'a':  int64
Type of 'b':  float64
Dimension of 'a': 1
Dimension of 'b': 1


In [40]:
# 2-dim array

studentdata = np.array([ ["Name", "Year", "Marks"], 
               ["Bela", 2014, 78.2],
                ["Joe", 1987, 59.1],
               ["Sugar", 1990, 70]])

print(studentdata)

print("Dimension of 'studentdata' :", np.ndim (studentdata))

[['Name' 'Year' 'Marks']
 ['Bela' '2014' '78.2']
 ['Joe' '1987' '59.1']
 ['Sugar' '1990' '70']]
Dimension of 'studentdata' : 2


In [45]:
import numpy as np
import pandas as pd

studentdata1 = {
                "Name": ["Bela", "Joe", "Sugar"],
                "Year": [2014, 1987, 1990],
                "Marks": [78.2, 59.1, 70]
               }

studentdata1_df = pd.DataFrame (studentdata1)
print (studentdata1_df)
print(type(np.array(studentdata1_df.Marks)))
print(np.mean(studentdata1_df.Marks))

    Name  Year  Marks
0   Bela  2014   78.2
1    Joe  1987   59.1
2  Sugar  1990   70.0
<class 'numpy.ndarray'>
69.10000000000001


In [46]:
a = np.array([ [11, 22, 33],
               [12, 24, 36],
               [13, 26, 39],
               [14, 28, 42],
               [15, 30, 45],
               [16, 32, 48]])

print (a)
print(a.shape)

[[11 22 33]
 [12 24 36]
 [13 26 39]
 [14 28 42]
 [15 30 45]
 [16 32 48]]
(6, 3)


In [47]:
print(np.shape(np.array(165416113)))

()


_Indexing_

In [50]:
import numpy as np

# One dimensional array
A = np.array([10, 21, 32, 43, 54, 65, 76, 87])

# Print the first element of A
print(A [0])
print(A[-1])

10
87


In [54]:
A = np.array ([ [1,2,3], [4,5,6], [7,8,9], [10,11,12] ])

print (A)
print(A [0])
print(A[-1])
print (A [2,1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3]
[10 11 12]
8


_Slicing_

In [57]:
# Consider a one-dimensional array A

A = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# By default, the step = 1

# To print the first 4 elements (i.e. indices 0, 1, 2, 3, those before index 4)
print(A [:4])

# To print the elements from the index = 6 till the end
print(A [6:])

# To print the elements starting from index=2 and it will stop BEFORE index=5

print(A [2:5])

# To print all the elements of the array
print(A [:])

# Introducing step = 2

# This will print alternate index elements of the entire array, starting from index = 0

print (A [::2])
print (A [::3])

[1 2 3 4]
[7 8]
[3 4 5]
[1 2 3 4 5 6 7 8]
[1 3 5 7]
[1 4 7]


In [61]:
# Consider a 2-dimensional

A = np.array([
["00", "01", "02", "03", "04"],
[10, 11, 12, 13, 14],
[20, 21, 22, 23, 24],
[30, 31, 32, 33, 34],
[40, 41, 42, 43, 44] 
])

print (A)

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']
 ['20' '21' '22' '23' '24']
 ['30' '31' '32' '33' '34']
 ['40' '41' '42' '43' '44']]


In [62]:
# Print a row or a column

print(A[1,])  # Printing Row 2

['10' '11' '12' '13' '14']


In [63]:
print(A[:,1]) # Column 2

['01' '11' '21' '31' '41']


In [64]:
# Print multiple rows or columns

print(A[:2,]) # Rows 1 & 2

print(A[:,1:3]) # Columns 2 & 3 

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']]
[['01' '02']
 ['11' '12']
 ['21' '22']
 ['31' '32']
 ['41' '42']]


In [65]:
# Print first or last rows and columns

print(A[:3,]) # Printing first three rows

print(A[:,3:]) # Printing 4th column and onwards 

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']
 ['20' '21' '22' '23' '24']]
[['03' '04']
 ['13' '14']
 ['23' '24']
 ['33' '34']
 ['43' '44']]


In [66]:
# Print selected rows and columns

print(A[:2,2]) # Rows 1 & 2 for column3

['02' '12']


In [67]:
print(A[:3,2:]) 

[['02' '03' '04']
 ['12' '13' '14']
 ['22' '23' '24']]


In [68]:
print(A[:,:-2])

[['00' '01' '02']
 ['10' '11' '12']
 ['20' '21' '22']
 ['30' '31' '32']
 ['40' '41' '42']]


In [69]:
print(A[:-3,:]) # Array without last 3 rows

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']]


_Using step_

In [72]:
# Let us create a new array using the arange method for this exercise

A2 = np.arange(50).reshape(5,10) # Create an array with 5 rows, 10 columns that has values from 0 to 49.

print(A2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [73]:
# Using step in slicing

print(A2[::2,]) # Print rows 1, 3, and 5

[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]
 [40 41 42 43 44 45 46 47 48 49]]


In [75]:
print(A2[:, 1:5:2]) # Print columns 2 & 4

[[ 1  3]
 [11 13]
 [21 23]
 [31 33]
 [41 43]]


In [76]:
print(A2[:, 1:10:2]) # Print columns 2,4, 6, 8, 10

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


In [77]:
# This will print an intersection of elements of rows 0, 2, 4 and columns 0, 3, 9, 6 

print(A2 [::2, ::3])

[[ 0  3  6  9]
 [20 23 26 29]
 [40 43 46 49]]


In [78]:
# Let us print all the rows and columns 

print (A2 [::,::])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [79]:
# If the following line of code is self explanatory to you, then you have understood the entire concept of 2D slicing

print (A2 [2:4:1, 2:7:4])

[[22 26]
 [32 36]]


In [81]:
# This should be self explanatory

A = np.arange(12)
B = A.reshape(3, 4)

A[0] = 42
print(B)

[[42  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


_Array of ones and zeros_

In [82]:
O = np.ones((4,4))
print(O)

# This is default datatype 'float'

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [83]:
O = np.ones((4,4), dtype=int) # Changing data type to integer
print(O)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [84]:
Z = np.zeros((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [85]:
Z = np.zeros((3,3), dtype=int)
print(Z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


_Identity function_

In [86]:
I = np.identity(4)

print (I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
