_Vectorization_

In [2]:
import numpy as np

my_list = [1, 2, 3, 4, 5.5, 6.6, 7.123, 8.456]

V = np.array(my_list)

print(V)

[1.    2.    3.    4.    5.5   6.6   7.123 8.456]


In [3]:
V_a = V + 2

print(V_a)

[ 3.     4.     5.     6.     7.5    8.6    9.123 10.456]


In [4]:
V_s = V - 2.4

print(V_s)

[-1.4   -0.4    0.6    1.6    3.1    4.2    4.723  6.056]


In [5]:
V2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

V_m = V2 * 10

print(V2)
print(V_m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [6]:
V_e = V2 ** 2

print(V_e)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [8]:
A = np.array([[1, 2, 3], [11, 22, 33], [111, 222, 333]])  # Array of shape 3,3
B = np.ones((3, 3), int)  # Array of shape 3,3
C = np.ones((4, 4))  # Array of shape 4,4
print(A)
print(B)
print(C)

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
print(A + B)

[[  2   3   4]
 [ 12  23  34]
 [112 223 334]]


In [10]:
print("Addition of 2 arrays of different shapes or dimensions will throw a ValueError.")

print(A + C)

Addition of 2 arrays of different shapes or dimensions will throw a ValueError.


ValueError: operands could not be broadcast together with shapes (3,3) (4,4) 

In [11]:
print("Subtracting array B from A is element wise: ")

print(A - B)

Subtracting array B from A is element wise: 
[[  0   1   2]
 [ 10  21  32]
 [110 221 332]]


In [13]:
A1 = np.array([[1, 2, 3], [4, 5, 6]])  # Array of shape 2,3
A2 = np.array([[1, 0, -1], [0, 1, -1]])  # Array of shape 2,3

print("Array 1\n", A1)
print("Array 2\n", A2)
print("Multiplying two arrays:\n", A1 * A2)

Array 1
 [[1 2 3]
 [4 5 6]]
Array 2
 [[ 1  0 -1]
 [ 0  1 -1]]
Multiplying two arrays:
 [[ 1  0 -3]
 [ 0  5 -6]]


_Broadcasting_

In [14]:
import numpy as np

A = np.array([[1, 2, 3], [11, 22, 33], [111, 222, 333]])
B = np.array([1, 2, 3])

print(A)
print(B)

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[1 2 3]


In [15]:
print("Multiplication with broadcasting: ")

print(A * B)

Multiplication with broadcasting: 
[[  1   4   9]
 [ 11  44  99]
 [111 444 999]]


In [16]:
print("... and now addition with broadcasting: ")

print(A + B)

... and now addition with broadcasting: 
[[  2   4   6]
 [ 12  24  36]
 [112 224 336]]


In [17]:
B = np.array([[1, 2, 3] * 3])

print(B)

[[1 2 3 1 2 3 1 2 3]]


In [18]:
B = np.array([1, 2, 3])
B[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [19]:
A * B[:, np.newaxis]

array([[  1,   2,   3],
       [ 22,  44,  66],
       [333, 666, 999]])

In [20]:
A = np.array([10, 20, 30])
B = np.array([1, 2, 3])
A[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [21]:
A[:, np.newaxis] * B

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [22]:
import numpy as np

A = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
B = np.array([[11, 102, 13], [201, 22, 203], [31, 32, 303]])

print(A)
print(B)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[ 11 102  13]
 [201  22 203]
 [ 31  32 303]]


In [23]:
A == B

array([[ True, False,  True],
       [False,  True, False],
       [ True,  True, False]])

In [24]:
print(np.array_equal(A, B))
print(np.array_equal(A, A))

False
True


In [25]:
a = np.array([[True, True], [False, False]])
b = np.array([[True, False], [True, False]])

print(np.logical_or(a, b))

[[ True  True]
 [ True False]]


In [26]:
print(np.logical_and(a, b))

[[ True False]
 [False False]]
